makeup_segments = [
    'SELECT REGION',
    'LEFT EYEBROW ONLY',
    'RIGHT EYEBROW ONLY',
    'BOTH EYEBROWS',
    'BOTH CHEEKS',
    'FACE BOUNDARY',
    'LIPS',
    'EYEBROWS AND CHEEKS',
    'EYEBROWS AND LIPS',
    'EYEBROWS, LIPS AND CHEEKS',
    'EYEBROWS, FACE BOUNDARY',
    'FACE BOUNDARY AND LIPS',
    'FACE BOUNDARY AND CHEEKS',
    'FACE BOUNDARY AND EYEBROWS',
    'ALL MAKEUP REGIONS (EYEBROWS, FACE BOUNDARY, CHEEKS, and LIPS)'

]